### PR TITLE
Support Poison ~> 1.5

### PR DESCRIPTION
**Pull request by jacegu**
Important packages (Phoenix I'm looking at you) still require you to be able to work with a 1.x version of Poison.

### CODE REVIEW

**Comment by jacegu** [comment]
@weppos in case you are wondering I'm working on a Phoenix app using our API and I faced this issue when trying to use the package with the latest Phoenix version:

```
* Updating dnsimple (git@github.com:aetrion/dnsimple-elixir.git)
Running dependency resolution

Failed to use "poison" (versions 2.0.0 to 2.1.0) because
  deps/dnsimple/mix.exs requires ~> 2.0
  phoenix (version 1.1.4) requires ~> 1.5 or ~> 2.0
  phoenix_ecto (version 2.0.1) requires ~> 1.3

** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock)
```

Turns out that `phoenix_ecto` doesn't support `2.x` versions of Poison yet. I've added support for Poison versions `~> 1.5` and verified that specs pass.

**Comment by weppos** [comment]
FYI, the reason I upgraded was a compilation issue. See https://github.com/aetrion/dnsimple-elixir/commit/fa7de6d179479873e671bf3ac830abcb0166a9c9

**Comment by jacegu** [comment]
That is odd. I just tried with the `1.5.2` version and I get no compilation warnings:

```
⌘ ~/Dev/dnsimple/api-elixir (➥ feature/poison-version ✗) ❯ mix deps.update poison
Running dependency resolution
Dependency resolution completed
  poison: 1.5.2
⌘ ~/Dev/dnsimple/api-elixir (➥ feature/poison-version ✗) ❯ mix compile
Compiled lib/dnsimple/account.ex
Compiled lib/dnsimple/domain_check.ex
Compiled lib/dnsimple/domain.ex
Compiled lib/dnsimple/identity_service.ex
Compiled lib/dnsimple/oauth_service.ex
Compiled lib/dnsimple/oauth_token.ex
Compiled lib/dnsimple/record.ex
Compiled lib/dnsimple/domains_service.ex
Compiled lib/dnsimple/registrar_auto_renewal_service.ex
Compiled lib/dnsimple/registrar_whois_privacy_service.ex
Compiled lib/dnsimple/registrar_service.ex
Compiled lib/dnsimple/user.ex
Compiled lib/dnsimple/response.ex
Compiled lib/dnsimple/whois_privacy.ex
Compiled lib/dnsimple/whoami.ex
Compiled lib/dnsimple/utils.ex
Compiled lib/dnsimple/zone.ex
Compiled lib/dnsimple.ex
Compiled lib/dnsimple/zones_service.ex
Generated dnsimple app
Consolidated Poison.Decoder
Consolidated List.Chars
Consolidated String.Chars
Consolidated Collectable
Consolidated Enumerable
Consolidated Poison.Encoder
Consolidated IEx.Info
Consolidated Inspect
```

Could it be related to the Elixir or Erlang versions?

**Comment by weppos** [comment]
Because it's not compiling your dependencies, they are likely already compiled. Try cloning the repo, or removing the `_build` folder.

**Comment by aeden** [comment]
`mix deps.clean` should also give you a fresh environment and require `mix deps.get`.

**Comment by jacegu** [comment]
My bad... Thought that getting a new version of Poison would force that.

After `mix deps.clean --all`, `mix deps.get` and `mix compile` I still get no error or warning. I've even verified that the compiled version of Poison was `1.5.2` in the `_build` directory...

**Comment by weppos** [comment]
@jacegu have you tried cloning the repo into a new folder?

Anyway, I'm fine to downgrade in order to support the current Phoenix version.

**Comment by jacegu** [comment]
The release of Phoenix 1.2 makes this unnecessary.

**Pull request closed without merging**
