### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the source of truth for this Elixir
library and leverage on latest features of ExDoc.

### CODE REVIEW

**Comment by OleMchls** [comment]
Hey @kianmeng thanks a bunch for your contributions. Going through these changes I wonder what's the source or reasoning for those changes. E.g. the license file name.

The current PR has a mix of things, that's too broad for me to accept as a whole.

**Comment by OleMchls** [comment]
I'd like to refrain from making changes to the licensefiles and legal texts in the repo. The other changes look good to me and I would be very happy to include those :)

**Comment by OleMchls** [comment]
Again, @kianmeng we appreciate your help with this, I've went forward merging your PR while not touching legal texts as mentioned before :)

**Comment by kianmeng** [comment]
> Hey @kianmeng thanks a bunch for your contributions. Going through these changes I wonder what's the source or reasoning for those changes. E.g. the license file name.
> 
> The current PR has a mix of things, that's too broad for me to accept as a whole.

@OleMchls 
Renaming `LICENSE.txt` to `LICENSE.md` so that it can be rendered accordingly as HTML through ExDoc. See screenshot below:

image

Note that the `mix.exs` still pointing to `LICENSE.md` and generating documentation will fail.
See https://github.com/dnsimple/dnsimple-elixir/blob/main/mix.exs#L52

**Comment by OleMchls** [comment]
@kianmeng thanks a lot for explaining this and spotting this mismatch. I've pushed a quick fix to `main` :)

**Pull request merged**
