### PR TITLE
Group module docs

### PR DESCRIPTION
**Pull request by patmaddox**
I checked out the docs and it took quite a while to find what I was looking for. Maybe it's just unfamiliarity with Elixir conventions (e.g. plural-named modules have functions, singular-named modules are data types). I grouped the modules in a way that I think would make them more immediate to someone wanting to use this library. I picked "API", "Data Types", and "Util" as the group names - I'm certainly open to different groupings or names, but this made sense to me.

## Before

image

## After

image

### CODE REVIEW

**Comment by OleMchls** [comment]
@patmaddox thanks so much for providing this <3 I like these additions a lot, I assigned @ecomba to review the categories you picked, and hopefully, we can include this with the upcoming test release of #175

**Review by ecomba — CHANGES_REQUESTED** [review]
Hey @patmaddox !

I really like how you've grouped the code, it makes it easier to navigate the docs; thank you so much!

What do you think of adding another section (for completeness sake) for the dnsimple specific errors? Not sure if this would be to much though (I'll let you decide).

One thing I would like you to do though is add what you did in the [CHANGELOG.md ](https://github.com/dnsimple/dnsimple-elixir/blob/main/CHANGELOG.md) as per our [CONTRIBUTING.md](https://github.com/dnsimple/dnsimple-elixir/blob/main/CONTRIBUTING.md).

**Comment by patmaddox** [comment]
> Hey @patmaddox !
> 
> I really like how you've grouped the code, it makes it easier to navigate the docs; thank you so much!
> 
> What do you think of adding another section (for completeness sake) for the dnsimple specific errors? Not sure if this would be to much though (I'll let you decide).

Mix docs already break errors out into their own `Exceptions` section at the bottom. Here's the bottom of the module list (original screenshot only shows the top). Unless you mean something else that I overlooked?

image

**Comment by patmaddox** [comment]
> One thing I would like you to do though is add what you did in the [CHANGELOG.md ](https://github.com/dnsimple/dnsimple-elixir/blob/main/CHANGELOG.md) as per our [CONTRIBUTING.md](https://github.com/dnsimple/dnsimple-elixir/blob/main/CONTRIBUTING.md).

Done! :)

**Comment by ecomba** [comment]
> > Hey @patmaddox !
> > I really like how you've grouped the code, it makes it easier to navigate the docs; thank you so much!
> > What do you think of adding another section (for completeness sake) for the dnsimple specific errors? Not sure if this would be to much though (I'll let you decide).
> 
> Mix docs already break errors out into their own `Exceptions` section at the bottom. Here's the bottom of the module list (original screenshot only shows the top). Unless you mean something else that I overlooked?
> 
> image

Duh... 😄

**Comment by ecomba** [comment]
> > One thing I would like you to do though is add what you did in the [CHANGELOG.md ](https://github.com/dnsimple/dnsimple-elixir/blob/main/CHANGELOG.md) as per our [CONTRIBUTING.md](https://github.com/dnsimple/dnsimple-elixir/blob/main/CONTRIBUTING.md).
> 
> Done! :)

Just a little update. Can you put the comment over the 3.1.0 section? Basically right under main.

When we prepare a release we set a new version, which will contain the changes in the changelog for that version.

Otherwise, everything looks great!

Thank you so much for this! 🙏🏼

**Comment by patmaddox** [comment]
> Just a little update. Can you put the comment over the 3.1.0 section? Basically right under main.

Done!

**Pull request merged**
