### PR TITLE
Adds the release workflow

### PR DESCRIPTION
**Pull request by ecomba**
Adds the automated release workflow.

When a new tag is pushed the release workflow will pick it up and start the releasing of the new version.

Things that need to be done (configuration wise), which I have no access to (we need someone with admin rights on this repo for that):

- [x] add the HEX_API_KEY to the secrets

### CODE REVIEW

**Review by OleMchls — APPROVED** [review]
These are almost impossible to test in a PR, I suggest releasing a patch version to test these action(s).

**Comment by OleMchls** [comment]
> > These are almost impossible to test in a PR, I suggest releasing a patch version to test these action(s).
> 
> Not sure how to do that @OleMchls . Can you advise?

Once this PR is merged, you generate a new release following this guide https://github.com/dnsimple/dnsimple-elixir/pull/175#issuecomment-993650275 increasing the _BugFix / Patch_ part by 1.

**Comment by ecomba** [comment]
> > > These are almost impossible to test in a PR, I suggest releasing a patch version to test these action(s).
> > 
> > 
> > Not sure how to do that @OleMchls . Can you advise?
> 
> Once this PR is merged, you generate a new release following this guide [#175 (comment)](https://github.com/dnsimple/dnsimple-elixir/pull/175#issuecomment-993650275) increasing the _BugFix / Patch_ part by 1.

Right, so we need to wait till we have the secrets added then. Thanks!

**Review by weppos — APPROVED** [review]
Added secret.

**Pull request merged**
