### PR TITLE
ignore .iex.exs

### PR DESCRIPTION
**Pull request by nesQuick**
This is super handy to setup a development iex session:

```
👌  dnsimple-elixir git:(elixir-dates) ✗ cat .iex.exs
client = %Dnsimple.Client{access_token: "NOT-MY-TOKEN!"}
account_id = 12345678
👌  dnsimple-elixir git:(elixir-dates) ✗ iex -S mix
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.3.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Dnsimple.Domains.list_domains(client, account_id)
....
```

### CODE REVIEW

**Comment by weppos** [comment]
@nesQuick I am curious, would you disable it on a per-project basis, or should it be a global gitignore setting?

**Comment by nesQuick** [comment]
I've no strong opinion about it, at some point I might also face a project where it does not make any sense to put something like described above. And then I'll add it to my global ignore 🗡 
I think this also points out the difference, for project with a clear use-case it makes sense to have it within the project (maybe even outline this in the README) and then some, like other pure libraries, I'd put it globally.

**Comment by weppos** [comment]
Actually, reading more about `.iex.exs`, it probably makes sense to keep it versioned _in general_.

In this particular case, I'm neutral, as we don't use this repo for example as a CLI.
In case of a CLI, I would see a potential benefit to let it versioned, and add for e.g. code to read the credentials into an env from a `.env` or from a `~/.local` or `~/.config`

**Comment by jacegu** [comment]
I'm ok with this.

I tried to do something similar in the past using a `.env` file for the sensitive data and versioning the `.ier.exs` file so everyone could benefit from it. However I think it's simpler to ignore it completely.

**Pull request merged**
