### PR TITLE
Update privacy param to private_whois for consistency

### PR DESCRIPTION
**Pull request by weppos**
See dnsimple/dnsimple-developer#58

/cc @jodosha @jacegu

### CODE REVIEW

**Comment by weppos** [comment]
@jacegu FYI it was a while since I downloaded this repo, I had to update the deps, and for some reason the whole mix.lock is now updated. Are you OK with me committing the changes?

**Comment by jodosha** [comment]
@weppos Actually, the param is `privacy` both on the developer site and the server side param.

**Comment by weppos** [comment]
@jodosha or the developer site there was a pending change since ages: https://github.com/dnsimple/dnsimple-developer/pull/58

**Comment by jodosha** [comment]
:shipit:

**Pull request merged**
