### PR TITLE
Client API follows conventions

### LINKED ISSUE #10: Mimic other language client's API
The idea is to be able to use the client like this:

```elixir
client = %Client{...}
Dnsimple.zones.list_zones(client, "_")
Dnsimple.zones.list_records(client, "_", "example.com")
```

instead of interacting with the service modules directly.

### PR DESCRIPTION
**Pull request by jacegu**
Closes #10 

This PR reviews all the existing module and function names to make sure that we follow the conventions in all clients. The summary would be:

- Get rid of the `Service` suffix. This way we can call functions like:

  ```elixir
  Dnsimple.Zones.create_record
  Dnsimple.Registrar.enable_auto_renewal
  ```

  This matches the function path and name that both the Ruby and Go clients have. The only difference is how the function is exposed (the `Dnsimple` module), which I think is normal given we are using a functional language:

  ```ruby
  client.zones.create_record
  client.registrar.enable_auto_renewal
  ```

  ```go
  client.Domains.ListDomains
  client.Registrar.EnableDomainAutoRenewal
  ```

  I think this is more idiomatic than defining `zones` or `registrar` as functions and returning the corresponding module.

- Consolidate function naming making sure we call methods and functions that do the same thing in all clients the same way. There are some that I still have to figure out because we have different names on each client.

### CODE REVIEW

**Comment by aeden** [comment]
👍  from me.

**Comment by jacegu** [comment]
One thing to consider is whether we want to move the structs to a separate directory and namespace like we have done in the Ruby client... e.g:

```
Dnsimple.Structs.Domain
Dnsimple.Structs.Identity
#...
```

I'm not 100% sure it's necessary but may make the code easier to navigate and understand.

**Comment by aeden** [comment]
@jacegu I don't think it's necessary at this time.

**Comment by weppos** [comment]
I'm fine to not more them now. I suggest we should release the lib as 0.9 (and not 1.0) so that we are still free to make such changes without a major bump.

I noticed you merged all the name spaced methods in the name space module. I'm fine with that, I just wanted to point out it may not be necessary.

Specifically, we may have

```
registrar.ex
registrar_foo.ex
registrar_bar.ex
```

all of them using the module `Dnsimple.Registrar` and having different methods (e.g one file for whois, one file for registration, etc).

We do that in all clients. In Ruby we use mixins, in Go we simply rely on the fact that the compiation will merge all of them together (pretty much as in Elixir). This is done mostly for code readability and organization.

**Comment by jacegu** [comment]
> in Go we simply rely on the fact that the compiation will merge all of them together (pretty much as in Elixir)

Unfortunately that is not the case. I wasn't 100% sure so I put this example together:

```elixir
defmodule A do
  def function_a, do: IO.puts("This is module #{inspect(__MODULE__)}")
end

defmodule A do
  def function_b, do: IO.puts("This is module #{inspect(__MODULE__)}")
end

A.function_b
A.function_a
```

This is the output:

```
⌘ ❯ elixir open_module_test.exs
warning: redefining module A (current version defined in memory)
  open_module_test.exs:5

This is module A
** (UndefinedFunctionError) function A.function_a/0 is undefined or private. Did you mean one of:

      * function_b/0

    A.function_a()
    (elixir) lib/code.ex:363: Code.require_file/2
```

In order to organize the code that way we will probably need to rely on some of Elixir's metaprogramming capabilities which I'm not sure is worth it given the length of the functions.

**Comment by weppos** [comment]
Oh, ok. So we cannot "reopen" a module. Then I'm fine to go with the current structure.

**Pull request merged**
